version: '3.8'
services:
  elk-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elk-node
    environment:
      - node.name=elk-node
      - cluster.name=elk-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.initial_master_nodes=elk-node
      - discovery.seed_hosts=elk-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-net
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    links:
      - qa-api
      - swagger
      - elk-node
    networks:
      - elastic-net
  qa-api:
    build: ./qa-api
    depends_on:
      - "elk-node"
    links:
      - elk-node
    networks:
      - elastic-net
    volumes:
      - ./data/:/tmp/data/
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    networks:
      - elastic-net

volumes:
  elastic-data:

networks:
  elastic-net:

