version: '3.8'
services:
  odfe-node:
    build:
      context: .
      dockerfile: Dockerfile.elastic
      args:
        OPEN_DISTRO_VERSION: ${OPEN_DISTRO_VERSION}
    image: odfe:${OPEN_DISTRO_VERSION}
    container_name: odfe-node
    environment:
      - node.name=odfe-node
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      #      - opendistro_security.ssl.http.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.initial_master_nodes=odfe-node
      - discovery.seed_hosts=odfe-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./odfe-data:/usr/share/elasticsearch/data
      #- ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      #- ./esnode.pem:/usr/share/elasticsearch/config/esnode.pem
      #- ./esnode-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      #- ./kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      #- ./kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
      #- ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
    ports:
      - "9200:9200"
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${OPEN_DISTRO_VERSION}
    container_name: odfe-kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    links:
      - odfe-node
    environment:
      ELASTICSEARCH_HOSTS: https://odfe-node:9200
      #volumes:
      #- ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - odfe-net
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    links:
      - qa-api
      - swagger
      - odfe-node
    networks:
      - odfe-net
  qa-api:
    build: ./qa-api
    depends_on:
      - "odfe-node"
    links:
      - odfe-node
    networks:
      - odfe-net
    volumes:
      - ./data/:/tmp/data/
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    networks:
      - odfe-net

volumes:
  odfe-data1:

networks:
  odfe-net:

