FROM nginx:1.19-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/ /etc/nginx/conf.d/
COPY nginx/nginxconfig.io/ /etc/nginx/nginxconfig.io/

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
