swagger: '2.0'
info:
  title: QA application
  version: '0.0.1'
  description: QA based on haystack-legacy
basePath: /
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:

  /askquestion:
    get:
      operationId: app.qa.ask_question
      summary: Asking question from NLP system
      parameters:
        - name: question
          in: query
          type: string
          required: true
          minimum: 1
          maximum: 3000
      responses:
        200:
          description: Return list of answers and contexts
          schema:
            type: array